### ISSUE TITLE
make.cmd

### ISSUE THREAD

**Issue by Alok-Dutt** [blacksheep-crm/siebelkeymaker#2]
line 23

%SSL%/openssl req -newkey rsa:2048 -keyout %SIEBEL%\%FQDN%\cakey.pem -out %SIEBEL%\%FQDN%\careq.pem -subj "/CN=%FQDN%" -sha256 -passout pass:%PASSWORD%

should be note the \

%SSL%\openssl req -newkey rsa:2048 -keyout %SIEBEL%\%FQDN%\cakey.pem -out %SIEBEL%\%FQDN%\careq.pem -subj "/CN=%FQDN%" -sha256 -passout pass:%PASSWORD%

**Comment by blacksheep-crm** [comment]
Thanks Alok, changed the code
